#### Example of use function - diferential evolution

In [1]:
from scipy.optimize import differential_evolution
import numpy as np
from calculate_error import calculate_error

MAE: 0.4166666666666667
RMSE: 0.8416254115301732
MSE: 0.7083333333333334


##### example parameters

In [2]:
bounds = [[-1, 2], [-1, 3], [0, 5], [1, 6], [-1, 6], [1, 8]]  # example bounds
mutation = 0.6  # example mutation parameter
recombination = 0.4  # example recombination parameter

In [3]:
result = differential_evolution(
    calculate_error, bounds, mutation=mutation, recombination=recombination
)

In [4]:
print(result)

             message: Optimization terminated successfully.
             success: True
                 fun: 1.850371707708594e-17
                   x: [ 1.000e+00  2.000e+00  3.000e+00  4.000e+00
                        5.000e+00  6.000e+00]
                 nit: 219
                nfev: 19933
          population: [[ 1.000e+00  2.000e+00 ...  5.000e+00  6.000e+00]
                       [ 1.000e+00  2.000e+00 ...  5.000e+00  6.000e+00]
                       ...
                       [ 1.000e+00  2.000e+00 ...  5.000e+00  6.000e+00]
                       [ 1.000e+00  2.000e+00 ...  5.000e+00  6.000e+00]]
 population_energies: [ 1.850e-17  1.850e-17 ...  1.850e-17  1.850e-17]


##### best predicted values

In [5]:
best_predicted_val = result.x
print(best_predicted_val)

[1. 2. 3. 4. 5. 6.]


##### value of the minimum target function

In [6]:
best_error = result.fun
print(best_error)

1.850371707708594e-17
